# Generated by Django 5.1.1 on 2024-09-17 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destiny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.travel')),
            ],
        ),
    ]
